query getIPAddress($id: ID!) {
  ipAddress(id: $id) {
    id
    ip
    reserved
    ipBlock {
      id
      prefix
      allowAutoAllocate
      allowAutoSubnet
    }
  }
}

mutation CreateIPAddress($input: CreateIPAddressInput!) {
  createIPAddress(input: $input) {
    ipAddress {
      id
      ip
      reserved
      ipBlock {
        id
        ipAddress {
          edges {
            node {
              id
              ip
            }
          }
        }
      }
    }
  }
}

mutation UpdateIPAddress($id: ID!, $input: UpdateIPAddressInput!) {
  updateIPAddress(id: $id, input: $input) {
    ipAddress {
      id
      ip
      reserved
      ipBlock {
        id
        ipAddress {
          edges {
            node {
              id
              ip
            }
          }
        }
      }
    }
  }
}

mutation DeleteIPAddress($id: ID!) {
  deleteIPAddress(id: $id) {
    deletedID
  }
}
