query GetIPBlock($id: ID!) {
  ipBlock(id: $id) {
    id
    prefix
    allowAutoSubnet
    allowAutoAllocate
    ipBlockType {
      id
    }
    ipAddress {
      edges {
        node {
          id
          ip
          reserved
        }
      }
    }
  }
}

mutation IPBlockCreate($input: CreateIPBlockInput!) {
  createIPBlock(input: $input) {
    ipBlock {
      id
      prefix
      allowAutoSubnet
      allowAutoAllocate
      ipBlockType {
        id
      }
      ipAddress {
        edges {
          node {
            id
            ip
            reserved
          }
        }
      }
    }
  }
}

mutation IPBlockUpdate($id: ID!, $input: UpdateIPBlockInput!) {
  updateIPBlock(id: $id, input: $input) {
    ipBlock {
      id
      prefix
      allowAutoSubnet
      allowAutoAllocate
      ipBlockType {
        id
      }
      ipAddress {
        edges {
          node {
            id
            ip
            reserved
          }
        }
      }
    }
  }
}

mutation IPBlockDelete($id: ID!) {
  deleteIPBlock(id: $id) {
    deletedID
  }
}
