package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"

	"go.infratographer.com/ipam-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// CreateIPAddress is the resolver for the createIPAddress field.
func (r *mutationResolver) CreateIPAddress(ctx context.Context, input generated.CreateIPAddressInput) (*IPAddressCreatePayload, error) {
	t, err := r.client.IPAddress.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &IPAddressCreatePayload{IPAddress: t}, err
}

// UpdateIPAddress is the resolver for the updateIPAddress field.
func (r *mutationResolver) UpdateIPAddress(ctx context.Context, id gidx.PrefixedID, input generated.UpdateIPAddressInput) (*IPAddressUpdatePayload, error) {
	t, err := r.client.IPAddress.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	t, err = t.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &IPAddressUpdatePayload{IPAddress: t}, err
}

// DeleteIPAddress is the resolver for the deleteIPAddress field.
func (r *mutationResolver) DeleteIPAddress(ctx context.Context, id gidx.PrefixedID) (*IPAddressDeletePayload, error) {
	if err := r.client.IPAddress.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, err
	}

	return &IPAddressDeletePayload{DeletedID: id}, nil
}

// IPAddress is the resolver for the ip_address field.
func (r *queryResolver) IPAddress(ctx context.Context, id gidx.PrefixedID) (*generated.IPAddress, error) {
	return r.client.IPAddress.Get(ctx, id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
