package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"

	"go.infratographer.com/ipam-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// CreateIPBlock is the resolver for the createIPBlock field.
func (r *mutationResolver) CreateIPBlock(ctx context.Context, input generated.CreateIPBlockInput) (*IPBlockCreatePayload, error) {
	t, err := r.client.IPBlock.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &IPBlockCreatePayload{IPBlock: t}, err
}

// UpdateIPBlock is the resolver for the updateIPBlock field.
func (r *mutationResolver) UpdateIPBlock(ctx context.Context, id gidx.PrefixedID, input generated.UpdateIPBlockInput) (*IPBlockUpdatePayload, error) {
	t, err := r.client.IPBlock.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	t, err = t.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &IPBlockUpdatePayload{IPBlock: t}, err
}

// DeleteIPBlock is the resolver for the deleteIPBlock field.
func (r *mutationResolver) DeleteIPBlock(ctx context.Context, id gidx.PrefixedID) (*IPBlockDeletePayload, error) {
	if err := r.client.IPBlock.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, err
	}

	return &IPBlockDeletePayload{DeletedID: id}, nil
}

// IPBlock is the resolver for the ip_block field.
func (r *queryResolver) IPBlock(ctx context.Context, id gidx.PrefixedID) (*generated.IPBlock, error) {
	return r.client.IPBlock.Get(ctx, id)
}
