package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"entgo.io/contrib/entgql"
	"go.infratographer.com/ipam-api/internal/ent/generated"
	"go.infratographer.com/ipam-api/internal/ent/generated/ipblocktype"
	"go.infratographer.com/x/gidx"
)

// Owner is the resolver for the owner field.
func (r *iPBlockTypeResolver) Owner(ctx context.Context, obj *generated.IPBlockType) (*Owner, error) {
	return &Owner{ID: obj.OwnerID}, nil
}

// IPBlockType is the resolver for the ip_block_type field.
func (r *ownerResolver) IPBlockType(ctx context.Context, obj *Owner, after *entgql.Cursor[gidx.PrefixedID], first *int, before *entgql.Cursor[gidx.PrefixedID], last *int, orderBy *generated.IPBlockTypeOrder, where *generated.IPBlockTypeWhereInput) (*generated.IPBlockTypeConnection, error) {
	return r.client.IPBlockType.Query().
		Where(
			ipblocktype.OwnerID(obj.ID),
		).Paginate(
		ctx,
		after,
		first,
		before,
		last,
		generated.WithIPBlockTypeOrder(orderBy),
		generated.WithIPBlockTypeFilter(where.Filter),
	)
}

// Owner returns OwnerResolver implementation.
func (r *Resolver) Owner() OwnerResolver { return &ownerResolver{r} }

type ownerResolver struct{ *Resolver }
