package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"entgo.io/contrib/entgql"
	"go.infratographer.com/ipam-api/internal/ent/generated"
	"go.infratographer.com/ipam-api/internal/ent/generated/ipblocktype"
	"go.infratographer.com/permissions-api/pkg/permissions"
	"go.infratographer.com/x/gidx"
)

// Owner is the resolver for the owner field.
func (r *iPBlockTypeResolver) Owner(ctx context.Context, obj *generated.IPBlockType) (*ResourceOwner, error) {
	return &ResourceOwner{ID: obj.OwnerID}, nil
}

// IPBlockType is the resolver for the ip_block_type field.
func (r *resourceOwnerResolver) IPBlockType(ctx context.Context, obj *ResourceOwner, after *entgql.Cursor[gidx.PrefixedID], first *int, before *entgql.Cursor[gidx.PrefixedID], last *int, orderBy *generated.IPBlockTypeOrder, where *generated.IPBlockTypeWhereInput) (*generated.IPBlockTypeConnection, error) {
	if err := permissions.CheckAccess(ctx, obj.ID, actionIPBlockTypeGet); err != nil {
		return nil, err
	}

	return r.client.IPBlockType.Query().
		Where(
			ipblocktype.OwnerID(obj.ID),
		).Paginate(
		ctx,
		after,
		first,
		before,
		last,
		generated.WithIPBlockTypeOrder(orderBy),
		generated.WithIPBlockTypeFilter(where.Filter),
	)
}

// ResourceOwner returns ResourceOwnerResolver implementation.
func (r *Resolver) ResourceOwner() ResourceOwnerResolver { return &resourceOwnerResolver{r} }

type resourceOwnerResolver struct{ *Resolver }
