version: "3.9"

volumes:
  crdb: null

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1.20-bullseye
        NODE_VERSION: "none"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    env_file:
      - .env
    depends_on:
      - crdb
      - nats
    volumes:
      - ./nsc:/nsc
      - ../..:/workspaces:cached
    # Port forwarded for local development with emacs tramp
    # ports:
    #   - "127.0.0.1:2222:2222"
    # Use "forwardPorts" in **devcontainer.json** to forward a port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # Environment setup
  create_databases:
    image: cockroachdb/cockroach:latest-v22.2
    restart: on-failure:5
    command: "sql --insecure -e 'CREATE DATABASE IF NOT EXISTS ipam_dev; CREATE DATABASE IF NOT EXISTS ipam_test; CREATE DATABASE IF NOT EXISTS atlas_migrations;'"
    env_file:
      - .env
    depends_on:
      - crdb

  # Required services (databases, etc)
  crdb:
    image: cockroachdb/cockroach:latest-v22.2
    command: start-single-node --insecure
    restart: unless-stopped
    volumes:
      - crdb:/cockroach/cockroach-data
    env_file:
      - .env
    healthcheck:
      test: "curl --fail http://localhost:8080/health?ready=1 || exit 1"
      interval: "2s"
      retries: 3
      start_period: "15s"
      timeout: "5s"

  nats-init:
    image: natsio/nats-box
    environment:
      - NSC_HOME=/nsc
    volumes:
      - ./nsc:/nsc
      - ./nats:/nats
      - ./scripts:/scripts
    command:
      - /scripts/nats_init.sh

  nats:
    image: 'nats:alpine'
    depends_on:
      - nats-init
    command:
      - -c
      - '/etc/nats/nats-server.conf'
      - -D
    volumes:
      - ./nats/:/etc/nats
    restart: unless-stopped
